# Generated by Django 2.0.2 on 2019-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mood_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='star',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
