# Generated by Django 2.0.2 on 2019-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mood_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='movie',
            field=models.CharField(choices=[('kabir_singh', 'KABIR_SINGH'), ('bharat', 'BHARAT'), ('avengers', 'AVENGERS'), ('golmaal', 'GOLMAL'), ('gadar', 'GADAR')], default='kabir_singh', max_length=100),
        ),
    ]
