# Generated by Django 2.0.2 on 2019-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mood_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='movie',
            field=models.CharField(choices=[('Kabir_Singh', 'Kabir_Singh'), ('Bharat', 'Bharat'), ('Avengers', 'Avengers'), ('Golmaal', 'Golmal'), ('Gadar', 'Gadar')], default='Select', max_length=100),
        ),
    ]
