# Generated by Django 2.0.2 on 2019-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190703_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='opinion',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
