# Generated by Django 2.0.2 on 2019-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mood_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='movie',
            field=models.CharField(choices=[('Kabir_Singh', 'Kabir_Singh'), ('Bharat', 'Bharat'), ('Avengers', 'Avengers')], default='Select', max_length=100),
        ),
    ]
